import type { WindowType } from './types'

const COMMON_METHODS = ['getSettings', 'onSettingsChanged'] as const

export const PRELOAD_API_METHODS: Record<WindowType, readonly string[]> = {
  pet: [
    ...COMMON_METHODS,
    'appendDebugLog',
    'setBubbleSettings',
    'getContextUsage',
    'onContextUsageChanged',
    'scanModels',
    'listTasks',
    'pauseTask',
    'resumeTask',
    'cancelTask',
    'dismissTask',
    'onTasksChanged',
    'triggerExpression',
    'triggerMotion',
    'onLive2dExpression',
    'onLive2dMotion',
    'onLive2dParamScript',
    'onLive2dMouseTarget',
    'reportLive2dCapabilities',
    'openChat',
    'openSettings',
    'setDisplayMode',
    'hideAll',
    'quit',
    'startDrag',
    'dragMove',
    'stopDrag',
    'showContextMenu',
    'setPetOverlayHover',
    'setPetModelHover',
    'onPetCursorProbe',
    'setIgnoreMouseEvents',
    'onBubbleMessage',
    'onBubblePreview',
    'onAsrHotkeyToggle',
    'reportAsrTranscript',
    'onAsrComposePreview',
    'ttsHttpGetJson',
    'ttsHttpRequestArrayBuffer',
    'ttsHttpStreamStart',
    'ttsHttpStreamCancel',
    'onTtsHttpStreamChunk',
    'onTtsHttpStreamDone',
    'onTtsHttpStreamError',
    'onTtsEnqueue',
    'onTtsFinalize',
    'onTtsStopAll',
    'reportTtsSegmentStarted',
    'reportTtsUtteranceEnded',
    'reportTtsUtteranceFailed',
  ],
  chat: [
    ...COMMON_METHODS,
    'appendDebugLog',
    'setMemorySettings',
    'setOrchestratorSettings',
    'setChatProfile',
    'setChatUiSettings',
    'getMcpState',
    'onMcpChanged',
    'setContextUsage',
    'getContextUsage',
    'onContextUsageChanged',
    'syncAsrComposePreview',
    'notifyAsrTranscriptReady',
    'takeAsrTranscript',
    'onAsrTranscript',
    'listChatSessions',
    'getChatSession',
    'createChatSession',
    'setCurrentChatSession',
    'renameChatSession',
    'deleteChatSession',
    'clearChatSession',
    'setChatMessages',
    'addChatMessage',
    'saveChatAttachment',
    'saveChatAttachmentFile',
    'readChatAttachmentDataUrl',
    'getChatAttachmentUrl',
    'updateChatMessage',
    'updateChatMessageRecord',
    'deleteChatMessage',
    'setChatAutoExtractCursor',
    'setChatAutoExtractMeta',
    'listTasks',
    'getTask',
    'updateTaskToolRunImages',
    'createTask',
    'pauseTask',
    'resumeTask',
    'cancelTask',
    'dismissTask',
    'onTasksChanged',
    'listPersonas',
    'getPersona',
    'updatePersona',
    'retrieveMemory',
    'upsertManualMemory',
    'triggerExpression',
    'triggerMotion',
    'openSettings',
    'openMemory',
    'closeCurrent',
    'sendBubbleMessage',
    'sendBubblePreview',
    'enqueueTtsUtterance',
    'finalizeTtsUtterance',
    'stopTtsAll',
    'onTtsSegmentStarted',
    'onTtsUtteranceEnded',
    'onTtsUtteranceFailed',
  ],
  settings: [
    ...COMMON_METHODS,
    'getDebugLogPath',
    'clearDebugLog',
    'setAlwaysOnTop',
    'setClickThrough',
    'setActivePersonaId',
    'setMemorySettings',
    'setPetScale',
    'setPetOpacity',
    'setLive2dModel',
    'setLive2dMouseTrackingEnabled',
    'setLive2dIdleSwayEnabled',
    'setAISettings',
    'setNovelAISettings',
    'saveAIProfile',
    'deleteAIProfile',
    'applyAIProfile',
    'listAIModels',
    'setBubbleSettings',
    'setTaskPanelSettings',
    'setOrchestratorSettings',
    'setToolSettings',
    'setMcpSettings',
    'getMcpState',
    'onMcpChanged',
    'setChatProfile',
    'setChatUiSettings',
    'setWorldBookSettings',
    'setTtsSettings',
    'listTtsOptions',
    'setAsrSettings',
    'scanModels',
    'listTasks',
    'onTasksChanged',
    'listPersonas',
    'getPersona',
    'createPersona',
    'updatePersona',
    'deletePersona',
    'listMemory',
    'upsertManualMemory',
    'deleteMemory',
    'triggerExpression',
    'triggerMotion',
    'openMemory',
    'closeCurrent',
  ],
  memory: [
    ...COMMON_METHODS,
    'setMemorySettings',
    'setMemoryConsoleSettings',
    'listChatSessions',
    'getChatSession',
    'setChatAutoExtractMeta',
    'listPersonas',
    'getPersona',
    'updatePersona',
    'listMemory',
    'upsertManualMemory',
    'updateMemory',
    'updateMemoryMeta',
    'updateManyMemoryMeta',
    'updateMemoryByFilterMeta',
    'listMemoryVersions',
    'rollbackMemoryVersion',
    'listMemoryConflicts',
    'resolveMemoryConflict',
    'deleteMemory',
    'deleteManyMemory',
    'deleteMemoryByFilter',
    'openSettings',
    'closeCurrent',
  ],
  orb: [
    ...COMMON_METHODS,
    'listChatSessions',
    'getChatSession',
    'createChatSession',
    'setCurrentChatSession',
    'deleteChatSession',
    'setChatMessages',
    'addChatMessage',
    'saveChatAttachment',
    'saveChatAttachmentFile',
    'readChatAttachmentDataUrl',
    'getChatAttachmentUrl',
    'updateChatMessage',
    'updateChatMessageRecord',
    'listTasks',
    'getTask',
    'createTask',
    'cancelTask',
    'onTasksChanged',
    'listPersonas',
    'getPersona',
    'retrieveMemory',
    'openChat',
    'openSettings',
    'setDisplayMode',
    'closeCurrent',
    'quit',
    'getOrbUiState',
    'setOrbUiState',
    'toggleOrbUiState',
    'setOrbOverlayBounds',
    'clearOrbOverlayBounds',
    'onOrbStateChanged',
    'showOrbContextMenu',
    'startDrag',
    'dragMove',
    'stopDrag',
  ],
  'orb-menu': [...COMMON_METHODS, 'openSettings', 'setDisplayMode', 'closeCurrent', 'quit'],
}

const WINDOW_TYPE_ARGUMENT_PREFIX = '--neodeskpet-window-type='

export function parsePreloadWindowType(argv: readonly string[]): WindowType | null {
  const raw = argv.find((arg) => arg.startsWith(WINDOW_TYPE_ARGUMENT_PREFIX))?.slice(WINDOW_TYPE_ARGUMENT_PREFIX.length)
  if (raw === 'pet' || raw === 'chat' || raw === 'settings' || raw === 'memory' || raw === 'orb' || raw === 'orb-menu') {
    return raw
  }
  return null
}

export function pickPreloadApi<T extends Record<string, unknown>>(api: T, windowType: WindowType): Partial<T> {
  const allowed = new Set(PRELOAD_API_METHODS[windowType])
  const exposed: Partial<T> = {}
  for (const [key, value] of Object.entries(api)) {
    if (allowed.has(key)) exposed[key as keyof T] = value as T[keyof T]
  }
  return exposed
}
